const generateId = () => {
    return '_' + Math.random().toString(36).substr(2, 9);
}

export default [ 
    {
        added_on: "29-01-2019",
        id: generateId(),
        title: "Maths Title",
        subject: "Maths",
        topic: "Ratios and Proportions",
        target_year: "2019",
        target_class: "X",
        price: 350,
        pages: "red",
        img: [{}],
        cover: "https://raw.githubusercontent.com/FGCDev/APet/master/src/res/imgs/covers/bio1.png",
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: ["class XIIth","12th", "Maths", "Ratios"],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    {
        added_on: "29-01-2019",
        id: generateId(),
        title: "Maths Title",
        subject: "Maths",
        topic: "Ratios and Proportions",
        target_year: "2019",
        cover: "https://raw.githubusercontent.com/FGCDev/APet/master/src/res/imgs/covers/bio1.png",
        target_class: "X",
        price: 350,
        pages: "red",
        img: [{}],
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: ["class XIIth","12th", "Maths", "Ratios"],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    {
        added_on: "29-01-2019",
        id: generateId(),
        title: "Fun with Ratios",
        cover: "https://raw.githubusercontent.com/FGCDev/APet/master/src/res/imgs/covers/bio1.png",
        subject: "Maths",
        topic: "Ratios and Proportions",
        target_year: "2019",
        target_class: "X",
        price: 350,
        pages: "red",
        img: [{}],
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: ["class XIIth","12th", "Maths", "Ratios"],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    {
        added_on: "29-01-2019",
        id: generateId(),
        title: "Maths Title",
        cover: "https://raw.githubusercontent.com/FGCDev/APet/master/src/res/imgs/covers/bio1.png",
        subject: "Maths",
        topic: "Ratios and Proportions",
        target_year: "2019",
        target_class: "X",
        price: 350,
        pages: "red",
        img: [{}],
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: ["class XIIth","12th", "Maths", "Ratios"],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    {
        added_on: "29-01-2019",
        id: generateId(),
        title: "Maths Title",
        subject: "Maths",
        cover: "https://raw.githubusercontent.com/FGCDev/APet/master/src/res/imgs/covers/bio1.png",
        topic: "Ratios and Proportions",
        target_year: "2019",
        target_class: "X",
        price: 350,
        pages: "red",
        img: [{}],
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: ["class XIIth","12th", "Maths", "Ratios"],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    {
        added_on: "29-01-2019",
        id: generateId(),
        title: "Science Title",
        subject: "Science",
        topic: "Ratios and Proportions",
        cover: "https://raw.githubusercontent.com/FGCDev/APet/master/src/res/imgs/covers/bio1.png",
        target_year: "2019",
        target_class: "X",
        price: 350,
        pages: "red",
        img: [{}],
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: [" "],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    
]