const generateId = () => {
    return Math.random().toString(36).substring(16) + (new Date()).getTime().toString(36);
}

export default [
    {
        added_on: "29-01-2019",
        id: () => generateId,
        title: "Maths Title",
        subject: "Maths",
        topic: "Ratios and Proportions",
        target_year: "2019",
        target_class: "X",
        price: "350",
        pages: "red",
        img: [{},{},{},{},{},{}],
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: ["class XIIth","12th", "Maths", "Ratios"],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    {
        added_on: "29-01-2019",
        id: () => generateId,
        title: "Maths Title",
        subject: "Maths",
        topic: "Ratios and Proportions",
        target_year: "2019",
        target_class: "X",
        price: "350",
        pages: "red",
        img: [{},{},{},{},{},{}],
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: ["class XIIth","12th", "Maths", "Ratios"],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    {
        added_on: "29-01-2019",
        id: () => generateId,
        title: "Maths Title",
        subject: "Maths",
        topic: "Ratios and Proportions",
        target_year: "2019",
        target_class: "X",
        price: "350",
        pages: "red",
        img: [{},{},{},{},{},{}],
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: ["class XIIth","12th", "Maths", "Ratios"],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    {
        added_on: "29-01-2019",
        id: () => generateId,
        title: "Maths Title",
        subject: "Maths",
        topic: "Ratios and Proportions",
        target_year: "2019",
        target_class: "X",
        price: "350",
        pages: "red",
        img: [{},{},{},{},{},{}],
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: ["class XIIth","12th", "Maths", "Ratios"],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    {
        added_on: "29-01-2019",
        id: () => generateId,
        title: "Maths Title",
        subject: "Maths",
        topic: "Ratios and Proportions",
        target_year: "2019",
        target_class: "X",
        price: "350",
        pages: "red",
        img: [{},{},{},{},{},{}],
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: ["class XIIth","12th", "Maths", "Ratios"],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    {
        added_on: "29-01-2019",
        id: () => generateId,
        title: "Maths Title",
        subject: "Maths",
        topic: "Ratios and Proportions",
        target_year: "2019",
        target_class: "X",
        price: "350",
        pages: "red",
        img: [{},{},{},{},{},{}],
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: ["class XIIth","12th", "Maths", "Ratios"],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    {
        added_on: "29-01-2019",
        id: () => generateId,
        title: "Maths Title",
        subject: "Maths",
        topic: "Ratios and Proportions",
        target_year: "2019",
        target_class: "X",
        price: "350",
        pages: "red",
        img: [{},{},{},{},{},{}],
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: ["class XIIth","12th", "Maths", "Ratios"],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    {
        added_on: "29-01-2019",
        id: () => generateId,
        title: "Maths Title",
        subject: "Maths",
        topic: "Ratios and Proportions",
        target_year: "2019",
        target_class: "X",
        price: "350",
        pages: "red",
        img: [{},{},{},{},{},{}],
        buyers: [],
        description: "Description of the book",
        reviews: ["I like this book","I love this book"],
        tags: ["class XIIth","12th", "Maths", "Ratios"],
        groups: ["Navratri special"],
        offers: ["20% off"],
        rating: "5",
        author: "Anonymous"
    },
    
]